[package]
name = "RustShims"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "rustshims"
crate-type = ["staticlib"]


[dependencies]
libc = "0.2"